### ISSUE TITLE
Not working on rhel 9.1

### ISSUE THREAD

**Issue by devisbal** [HewlettPackard/LinuxKI#52]
Note: Solution tested and working.
r->rq_disk. It can now be accessed through r->q->disk
#define GENDISK r->q->disk

Error was:
# ./module_prep
        Unable to find compatible module - attempting to build from source ...
hostkernel=5.14.0-162.6.1.el9_1.x86_64
hostdistro=rhel
hostversion=9.1
EXTRA_CFLAGS=-g -O3 -Wall -DHARDCLOCK_STACK_SKIP=8 -DOTHER_STACK_SKIP=2
make -C /lib/modules/5.14.0-162.6.1.el9_1.x86_64/build  M=/tmp/tmp.Nu3mx0EhmZ   modules
make[1]: Entering directory '/usr/src/kernels/5.14.0-162.6.1.el9_1.x86_64'
hostkernel=5.14.0-162.6.1.el9_1.x86_64
hostdistro=rhel
hostversion=9.1
EXTRA_CFLAGS=-g -O3 -Wall -DHARDCLOCK_STACK_SKIP=8 -DOTHER_STACK_SKIP=2
Building with KERNELRELEASE = 5.14.0-162.6.1.el9_1.x86_64
  CC [M]  /tmp/tmp.Nu3mx0EhmZ/likit.o
/tmp/tmp.Nu3mx0EhmZ/likit.c: In function ‘block_rq_insert_trace’:
/tmp/tmp.Nu3mx0EhmZ/likit.c:2698:18: error: ‘struct request’ has no member named ‘rq_disk’
 2698 | #define GENDISK r->rq_disk
      |                  ^~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2773:31: note: in expansion of macro ‘GENDISK’
 2773 |                 dev_t   dev = GENDISK ? disk_devt(GENDISK) : 0;
      |                               ^~~~~~~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2698:18: error: ‘struct request’ has no member named ‘rq_disk’
 2698 | #define GENDISK r->rq_disk
      |                  ^~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2773:51: note: in expansion of macro ‘GENDISK’
 2773 |                 dev_t   dev = GENDISK ? disk_devt(GENDISK) : 0;
      |                                                   ^~~~~~~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2698:18: error: ‘struct request’ has no member named ‘rq_disk’
 2698 | #define GENDISK r->rq_disk
      |                  ^~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2714:18: note: in expansion of macro ‘GENDISK’
 2714 |         T->dev = GENDISK ? disk_devt(GENDISK) : 0;                              \
      |                  ^~~~~~~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2796:9: note: in expansion of macro ‘POPULATE_COMMON_BLOCK_FIELDS’
 2796 |         POPULATE_COMMON_BLOCK_FIELDS(q, r, t);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2698:18: error: ‘struct request’ has no member named ‘rq_disk’
 2698 | #define GENDISK r->rq_disk
      |                  ^~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2714:38: note: in expansion of macro ‘GENDISK’
 2714 |         T->dev = GENDISK ? disk_devt(GENDISK) : 0;                              \
      |                                      ^~~~~~~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2796:9: note: in expansion of macro ‘POPULATE_COMMON_BLOCK_FIELDS’
 2796 |         POPULATE_COMMON_BLOCK_FIELDS(q, r, t);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/tmp.Nu3mx0EhmZ/likit.c: In function ‘block_rq_issue_trace’:
/tmp/tmp.Nu3mx0EhmZ/likit.c:2698:18: error: ‘struct request’ has no member named ‘rq_disk’
 2698 | #define GENDISK r->rq_disk
      |                  ^~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2839:31: note: in expansion of macro ‘GENDISK’
 2839 |                 dev_t   dev = GENDISK ? disk_devt(GENDISK) : 0;
      |                               ^~~~~~~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2698:18: error: ‘struct request’ has no member named ‘rq_disk’
 2698 | #define GENDISK r->rq_disk
      |                  ^~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2839:51: note: in expansion of macro ‘GENDISK’
 2839 |                 dev_t   dev = GENDISK ? disk_devt(GENDISK) : 0;
      |                                                   ^~~~~~~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2698:18: error: ‘struct request’ has no member named ‘rq_disk’
 2698 | #define GENDISK r->rq_disk
      |                  ^~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2714:18: note: in expansion of macro ‘GENDISK’
 2714 |         T->dev = GENDISK ? disk_devt(GENDISK) : 0;                              \
      |                  ^~~~~~~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2857:9: note: in expansion of macro ‘POPULATE_COMMON_BLOCK_FIELDS’
 2857 |         POPULATE_COMMON_BLOCK_FIELDS(q, r, t);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2698:18: error: ‘struct request’ has no member named ‘rq_disk’
 2698 | #define GENDISK r->rq_disk
      |                  ^~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2714:38: note: in expansion of macro ‘GENDISK’
 2714 |         T->dev = GENDISK ? disk_devt(GENDISK) : 0;                              \
      |                                      ^~~~~~~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2857:9: note: in expansion of macro ‘POPULATE_COMMON_BLOCK_FIELDS’
 2857 |         POPULATE_COMMON_BLOCK_FIELDS(q, r, t);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/tmp.Nu3mx0EhmZ/likit.c: In function ‘block_rq_complete_trace’:
/tmp/tmp.Nu3mx0EhmZ/likit.c:2698:18: error: ‘struct request’ has no member named ‘rq_disk’
 2698 | #define GENDISK r->rq_disk
      |                  ^~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2914:31: note: in expansion of macro ‘GENDISK’
 2914 |                 dev_t   dev = GENDISK ? disk_devt(GENDISK) : 0;
      |                               ^~~~~~~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2698:18: error: ‘struct request’ has no member named ‘rq_disk’
 2698 | #define GENDISK r->rq_disk
      |                  ^~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2914:51: note: in expansion of macro ‘GENDISK’
 2914 |                 dev_t   dev = GENDISK ? disk_devt(GENDISK) : 0;
      |                                                   ^~~~~~~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2698:18: error: ‘struct request’ has no member named ‘rq_disk’
 2698 | #define GENDISK r->rq_disk
      |                  ^~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2714:18: note: in expansion of macro ‘GENDISK’
 2714 |         T->dev = GENDISK ? disk_devt(GENDISK) : 0;                              \
      |                  ^~~~~~~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2932:9: note: in expansion of macro ‘POPULATE_COMMON_BLOCK_FIELDS’
 2932 |         POPULATE_COMMON_BLOCK_FIELDS(q, r, t);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2698:18: error: ‘struct request’ has no member named ‘rq_disk’
 2698 | #define GENDISK r->rq_disk
      |                  ^~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2714:38: note: in expansion of macro ‘GENDISK’
 2714 |         T->dev = GENDISK ? disk_devt(GENDISK) : 0;                              \
      |                                      ^~~~~~~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2932:9: note: in expansion of macro ‘POPULATE_COMMON_BLOCK_FIELDS’
 2932 |         POPULATE_COMMON_BLOCK_FIELDS(q, r, t);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/tmp.Nu3mx0EhmZ/likit.c: In function ‘block_rq_requeue_trace’:
/tmp/tmp.Nu3mx0EhmZ/likit.c:2698:18: error: ‘struct request’ has no member named ‘rq_disk’
 2698 | #define GENDISK r->rq_disk
      |                  ^~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2986:31: note: in expansion of macro ‘GENDISK’
 2986 |                 dev_t   dev = GENDISK ? disk_devt(GENDISK) : 0;
      |                               ^~~~~~~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2698:18: error: ‘struct request’ has no member named ‘rq_disk’
 2698 | #define GENDISK r->rq_disk
      |                  ^~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2986:51: note: in expansion of macro ‘GENDISK’
 2986 |                 dev_t   dev = GENDISK ? disk_devt(GENDISK) : 0;
      |                                                   ^~~~~~~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2698:18: error: ‘struct request’ has no member named ‘rq_disk’
 2698 | #define GENDISK r->rq_disk
      |                  ^~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2714:18: note: in expansion of macro ‘GENDISK’
 2714 |         T->dev = GENDISK ? disk_devt(GENDISK) : 0;                              \
      |                  ^~~~~~~
/tmp/tmp.Nu3mx0EhmZ/likit.c:3004:9: note: in expansion of macro ‘POPULATE_COMMON_BLOCK_FIELDS’
 3004 |         POPULATE_COMMON_BLOCK_FIELDS(q, r, t);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2698:18: error: ‘struct request’ has no member named ‘rq_disk’
 2698 | #define GENDISK r->rq_disk
      |                  ^~
/tmp/tmp.Nu3mx0EhmZ/likit.c:2714:38: note: in expansion of macro ‘GENDISK’
 2714 |         T->dev = GENDISK ? disk_devt(GENDISK) : 0;                              \
      |                                      ^~~~~~~
/tmp/tmp.Nu3mx0EhmZ/likit.c:3004:9: note: in expansion of macro ‘POPULATE_COMMON_BLOCK_FIELDS’
 3004 |         POPULATE_COMMON_BLOCK_FIELDS(q, r, t);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:295: /tmp/tmp.Nu3mx0EhmZ/likit.o] Error 1
make[1]: *** [Makefile:1915: /tmp/tmp.Nu3mx0EhmZ] Error 2
make[1]: Leaving directory '/usr/src/kernels/5.14.0-162.6.1.el9_1.x86_64'
make: *** [Makefile:262: build] Error 2
insmod: ERROR: could not load module likit.ko: No such file or directory

**Comment by MarkCRay** [comment]
Indeed, version 7.5  did not include support for RHEL 9.1.    I'll add that in LinuxKI version 7.6.     The problem occurs because Redhat pulled in upstream changes from 5.16 into their 5.14 code base.   I had already fixed this in 5.16 kernels.

As a workaround for RHEL 9.1 ONLY, you can change the KERNEL_VERSION below to 5,14,0

#if LINUX_VERSION_CODE >= KERNEL_VERSION(5,16,0)
#define GENDISK q->disk
#else
#define GENDISK r->rq_disk
#endif

Just remember that I haven't tested RHEL 9.1 yet.    So you'll be the first one to try.

**Comment by MarkCRay** [comment]
This will be fixed in version 7.6.   Hope to have it ready soon.

**Comment by MarkCRay** [comment]
Fixed in version 7.6 released on 2/24/2023
