### ISSUE TITLE
linuxki fails to build on centos 8.2 

### ISSUE THREAD

**Issue by kachini** [HewlettPackard/LinuxKI#34]
linuxki 6.1 fails to build on centos 8.2 and it seems it need to have flag "-DRHEL82"

/opt/linuxki/src/liki/likit.c:6864:2: error: implicit declaration of function ‘synchronize_sched’; did you mean ‘synchronize_net’? [-Werror=implicit-function-declaration]
  synchronize_sched();
  ^~~~~~~~~~~~~~~~~
  synchronize_net

**Comment by MarkCRay** [comment]
Thanks.   Its a simply change the the liki Makefile.    Will be fixed in the next release.    Until then, here's the Makefile section for CentOS to follow the RHEL section:

else ifeq ($(hostdistro),centos) #  Centos
   ifneq (,$(findstring 6.,$(hostversion)))
      #RHEL6 (2.6)
      EXTRA_CFLAGS=-g -O3 -Wall -DHARDCLOCK_STACK_SKIP=8 -DOTHER_STACK_SKIP=2
   else ifneq (,$(findstring 7.,$(hostversion)))
      #RHEL 7 (3.10)
      EXTRA_CFLAGS=-g -O3 -Wall -DHARDCLOCK_STACK_SKIP=0 -DOTHER_STACK_SKIP=2
   else ifneq (,$(findstring 8.0,$(hostversion)))
      #RHEL 8.0 (4.18)
      EXTRA_CFLAGS=-g -O3 -Wall -DRHEL8 -DHARDCLOCK_STACK_SKIP=8 -DOTHER_STACK_SKIP=2
   else ifneq (,$(findstring 8.1,$(hostversion)))
      #RHEL 8.1(4.18)
      EXTRA_CFLAGS=-g -O3 -Wall -DRHEL8 -DHARDCLOCK_STACK_SKIP=8 -DOTHER_STACK_SKIP=2
   else ifneq (,$(findstring 8.,$(hostversion)))
      #RHEL 8 (4.18)
      EXTRA_CFLAGS=-g -O3 -Wall -DRHEL82 -DHARDCLOCK_STACK_SKIP=0 -DOTHER_STACK_SKIP=2
   endif

**Comment by MarkCRay** [comment]
This is now fixed in LinuxKI version 6.2, released 10/16/2020.
